version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/
#      SPRING_DATASOURCE_USERNAME:
#      SPRING_DATASOURCE_PASSWORD: